### ISSUE TITLE
how to get z1 z2 value

### ISSUE THREAD

**Issue by timekswaste** [nlitsme/bitcoinexplainer#1]
-txid f9aa66876f79ed8870720e9019e769548f591d285cc2d16460c411c5da0912ca
R: 6fc545a0360d77a92e5f00ad13f947c48d3d61605b091f43d3b8c9aeca68a3ea
S: 472db6ab16c4b34442a123764e871bbf1c866810996a3117c7a4937ef0b92b52
Z: 49acf9eb7e34189460d96ef1d8ce0d6bd35e5ff659da757775244aeb887b398d
PubKey: 0242ae9c0bd6300b20b08709546b79a02ef3a297a7eee1299121e2f79eb646c5b

i need this rsz private key
how to rsz to hex private key get in python

and explain how to get z1 and z2 -txid f9aa66876f79ed8870720e9019e769548f591d285cc2d16460c411c5da0912ca

**Comment by timekswaste** [comment]
run this script https://github.com/FoxxD3V/btc-rsz/blob/master/RawTX_RSZ.py
output : show r s1s2 z1,z2
but i got error what my mistake

https://tbtc.bitaps.com/raw/transaction/ff948290ff332aed8f0e5d767118a02e8671578c6775a333bb4ee4d6ccfcf639
i am enter raw tx i got error https://github.com/FoxxD3V/btc-rsz/blob/master/RawTX_RSZ.py
Traceback (most recent call last):
File "RawTX_RSZ.py", line 13, in
s = keyUtils.derSigToHexSig(m[1][:-2])
File "/home/runner/btc-rsz/keyUtils.py", line 32, in derSigToHexSig
x, s = ecdsa.der.remove_integer(s)
File "/usr/local/lib/python2.7/dist-packages/ecdsa/der.py", line 218, in remove_integer
raise UnexpectedDER("Negative integers are not supported")
ecdsa.der.UnexpectedDER: Negative integers are not supported

i know r s1s2
i need z1z2 value,please how to get z1z2 #mybadenglish

**Comment by nlitsme** [comment]
You need a 2nd transaction using the same r value.   and as far as I can tell, there is none in the main-net bitcoin blockchain.

And, btw your pubkey is missing a '9' at the end.

**Comment by timekswaste** [comment]
tq reply @nlitsme
 iam watch this video https://www.youtube.com/watch?v=iLRbLKfRqwA only one rsz and public key use crack private key : its possible i dont know ,any idea find k,pk formula
i just copy the code in this video
#sagemath_method_crack
p = 0x
n = 0x

E = EllipticCurve(GF(p), [0, 7])
Fn = FiniteField(n)
xP = 0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798
yP = 0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8

r = 0x
s = 0x
p = 0x #enter publickery 02 0r 03 /04 maybe

k = (()) #i dont know p,pk formula ,any idea guess
pk = ()
print(hex(pk))

video link not work i am backup this video click https://drive.google.com/file/d/10kqJp_Eiqf6s_7IU5T2WnthThF5b4srg/view?usp=sharing

**Comment by nlitsme** [comment]
the claim in that video is that he cracked this wallet: https://bitaps.com/1P5ZEDWTKTFGxQjZphgWPQUpe554WKDfHQ
Then why is it still full of bitcoins?

There is no such formula.

**Comment by timekswaste** [comment]
Block Chain WebSocket Listener
https://github.com/AvalerionV/bitcoin-bruteforce this project currently working or not,any improvement i am run 1hr

**Comment by timekswaste** [comment]
> Block Chain WebSocket Listener https://github.com/AvalerionV/bitcoin-bruteforce this project currently working or not,any improvement i am run 1hr

update please..

**Comment by nlitsme** [comment]
the video uses just one transaction.  there is no formula to crack a key from just one txn. 

That link which says 'bruteforce'  sends the values to https://code.hackhex.com/log.php  and does nothing else as far as I can see.

**Comment by Jaloliddin-jp** [comment]
Hi! You should search z1 and z2 from second transaction !

**Comment by Jaloliddin-jp** [comment]
k = (()) #i dont know p,pk formula ,any idea guess   
 
And about this formula ! I know but this formula isn't everything ! Because we should find second formula i mean (pk) !
