### ISSUE TITLE
Decimal & Hexadecimal

### ISSUE THREAD

**Issue by RoyNahar** [nlitsme/bitcoinexplainer#4]
It is weird that when i input my values in here https://rawcdn.githack.com/nlitsme/bitcoinexplainer/aa50e86e8c72c04a7986f5f7c43bc2f98df94107/ecdsacrack.html in decimal and hexadecimal format,  i get 2 different answers. i think you should inform the users on that site to use hexadecimal, if they want a correct answer. i just realise this about a month ago and since i did not see anyone bringing this up, i thought you should know. anyways, great work, thank you.

**Comment by nlitsme** [comment]
added clarification.
